### PR TITLE
Upgrade terraform-provider-kafka to v0.5.4

### LINKED ISSUE #192: scram user creation (Upgrade terraform-provider-kafka to v0.5.3)
We are running our own fork of pulumi-kafka to be able to create Scram user and it's causing some headache.
Ideally, we can use the official provider to achieve that.

I understand that's blocked by https://github.com/pulumi/pulumi-kafka/issues/145

But i wonder if this is a real issue at all? We are not able to reproduce ourselves. we have also been using 0.5.3 in prod for managing Kafka creation in other prod workloads for quite some time now.

It would be a huge unblock if pulumi-kafka can support scram user creation.

Thanks!

### LINKED ISSUE #194: Upgrade terraform-provider-kafka to v0.5.4
Release details: https://github.com/Mongey/terraform-provider-kafka/releases/tag/v0.5.4

### PR DESCRIPTION
**Pull request by rquitales**
This PR was generated via `$ upgrade-provider pulumi/pulumi-kafka --kind=all`, with some manual changes required.

---

- Upgrading terraform-provider-kafka from 0.5.2  to 0.5.4.
	Fixes #194
        Fixes #192
- Upgrading pulumi-terraform-bridge from v3.38.1 to v3.57.0.
- Upgrading pulumi-terraform-bridge/pf from  to v3.57.0.
- Upgrading pulumi/terraform-plugin-sdk from v2.24.1 to 2.27.0.
- Upgrade wurstmeister/kafka to 2.13-2.8.1 for use in our tests

### CODE REVIEW

**Review by iwahbe — COMMENTED** [review]
Can we add token auto-mapping instead of more explicit resources?

**Review by lukehoban — APPROVED** [review]

**Comment by rquitales** [comment]
> Can we add token auto-mapping instead of more explicit resources?

Done! And removed the new resource to test that it works as expected as well.

**Review by thomas11 — COMMENTED** [review]
Seems like lost a number of examples, e.g. in sdk/dotnet/Acl.cs, sdk/dotnet/Quota.cs, sdk/dotnet/Topic.cs, sdk/go/kafka/acl.go, etc.

That's a bit of a regression for our users. Can we try and see what happened?

**Review by iwahbe — APPROVED** [review]
Can you confirm that the missing docs were not removed upstream. If they should be in this provider, please make an issue in `pulumi-kafka` and add it to https://github.com/pulumi/pulumi-terraform-bridge/issues/1290. Lets not block on the missing docs.

LGTM

**Comment by iwahbe** [comment]
Docs regression seems to be caused by https://github.com/Mongey/terraform-provider-kafka/commit/8b8961dcaa68d8b4089d6f905acaa9f972dd3715.

**Pull request merged**
